Clarify custom domain docs
wedeploy/docs pull request #49
Opened 2016-11-07 19:52 UTC by liftedkilt

2016-11-07 21:03 UTC, zenorocha requested changes

2016-11-07 21:03 UTC, zenorocha commented on intro/custom-domains.md
> +WeDeploy automatically creates a subdomain for each service. Since you typically will have multiple services inside a project, you will either need multiple records, or a single Wildcard record. A wi
`wedeploy` > `WeDeploy`

2016-11-07 21:03 UTC, zenorocha commented on intro/custom-domains.md
> +WeDeploy automatically creates a subdomain for each service. Since you typically will have multiple services inside a project, you will either need multiple records, or a single Wildcard record. A wi
`single Wildcard record` > `single wildcard record`

2016-11-07 21:04 UTC, zenorocha commented
Thanks for the PR @liftedkilt!

2016-11-08 01:53 UTC, liftedkilt commented
@zenorocha fixed. Thanks for catching that.

2016-11-08 01:53 UTC, zenorocha commented
Thanks!!

2016-11-08 01:53 UTC, merged

2016-11-08 08:08 UTC, eduardolundgren commented
@liftedkilt thanks!